-- llmlog schema.
-- bootstrapSchema() is expected to run against a freshly created database,
-- so DDL below does not use IF NOT EXISTS. The one-true-idempotent PSQL
-- objects (procedures, exceptions) use CREATE OR ALTER.

-- ---------------------------------------------------------------------------
-- PROVIDERS: upstream LLM API vendors
-- ---------------------------------------------------------------------------
CREATE TABLE PROVIDERS (
    ID          SMALLINT     NOT NULL PRIMARY KEY,
    NAME        VARCHAR(32)  NOT NULL UNIQUE,
    BASE_URL    VARCHAR(128) NOT NULL,
    -- 'anthropic' | 'openai' | 'gemini' | 'openai_compat'
    KIND        VARCHAR(16)  NOT NULL
);

-- ---------------------------------------------------------------------------
-- MODELS: specific model identifiers per provider
-- ---------------------------------------------------------------------------
CREATE TABLE MODELS (
    ID           INTEGER      NOT NULL PRIMARY KEY,
    PROVIDER_ID  SMALLINT     NOT NULL,
    MODEL_ID     VARCHAR(96)  NOT NULL, -- e.g. 'claude-opus-4-7', 'gpt-5-turbo'
    FAMILY       VARCHAR(32),           -- e.g. 'claude-opus', 'gpt-5'
    CONSTRAINT FK_MODELS_PROVIDER FOREIGN KEY (PROVIDER_ID) REFERENCES PROVIDERS(ID),
    CONSTRAINT UNQ_MODELS_PROVIDER_MODEL UNIQUE (PROVIDER_ID, MODEL_ID)
);

-- ---------------------------------------------------------------------------
-- PRICING: historical price table; SP_GET_EFFECTIVE_PRICING picks the latest
-- row with EFFECTIVE_FROM <= CALL_TIME. Prices are $ per 1,000,000 tokens.
-- DECFLOAT(34) preserves exact unit price through unlimited aggregation.
-- ---------------------------------------------------------------------------
CREATE TABLE PRICING (
    MODEL_ID             INTEGER     NOT NULL,
    EFFECTIVE_FROM       TIMESTAMP WITH TIME ZONE NOT NULL,
    INPUT_PER_MTOK       DECFLOAT(34) NOT NULL,
    OUTPUT_PER_MTOK      DECFLOAT(34) NOT NULL,
    CACHE_READ_PER_MTOK  DECFLOAT(34),
    CACHE_WRITE_PER_MTOK DECFLOAT(34),
    IMAGE_PER_MTOK       DECFLOAT(34),
    NOTE                 VARCHAR(256),
    CONSTRAINT PK_PRICING PRIMARY KEY (MODEL_ID, EFFECTIVE_FROM),
    CONSTRAINT FK_PRICING_MODEL FOREIGN KEY (MODEL_ID) REFERENCES MODELS(ID)
);

-- ---------------------------------------------------------------------------
-- REQUESTS: one row per logged upstream API call. COST_USD is computed once at
-- insert time via SP_LOG_REQUEST and stored permanently; historical price
-- changes therefore never retroactively alter ledger numbers.
-- ---------------------------------------------------------------------------
CREATE TABLE REQUESTS (
    ID              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CALL_TIME       TIMESTAMP WITH TIME ZONE NOT NULL,
    MODEL_ID        INTEGER     NOT NULL,
    REQUEST_ID      VARCHAR(96),
    INPUT_TOKENS    BIGINT      NOT NULL DEFAULT 0,
    OUTPUT_TOKENS   BIGINT      NOT NULL DEFAULT 0,
    CACHE_READ      BIGINT      NOT NULL DEFAULT 0,
    CACHE_WRITE     BIGINT      NOT NULL DEFAULT 0,
    IMAGE_TOKENS    BIGINT      NOT NULL DEFAULT 0,
    LATENCY_MS      INTEGER     NOT NULL,
    HTTP_STATUS     SMALLINT    NOT NULL,
    COST_USD        DECFLOAT(34) NOT NULL,
    TAG             VARCHAR(64),
    CONSTRAINT FK_REQUESTS_MODEL FOREIGN KEY (MODEL_ID) REFERENCES MODELS(ID)
);

CREATE INDEX IDX_REQUESTS_TIME  ON REQUESTS (CALL_TIME);
CREATE INDEX IDX_REQUESTS_MODEL ON REQUESTS (MODEL_ID, CALL_TIME);
CREATE INDEX IDX_REQUESTS_TAG   ON REQUESTS (TAG, CALL_TIME);
